/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chippedanimals.frontend;

import chippedanimals.backend.ChippedAnimal;
import chippedanimals.backend.Database;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JOptionPane;

/**
 *
 * @author lunie
 */
public class EditAnimalFrame extends javax.swing.JFrame implements KeyListener {

    /**
     * Creates new form AddAnimalFrame
     */
    public EditAnimalFrame() {
        initComponents();
        db = new Database();
        
        InputID.addKeyListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        bEdit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        InputName = new javax.swing.JTextField();
        InputChip = new javax.swing.JTextField();
        InputPhone = new javax.swing.JTextField();
        InputEmail = new javax.swing.JTextField();
        cbxKind = new javax.swing.JComboBox<>();
        InputID = new javax.swing.JTextField();
        lID = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lWarning = new javax.swing.JLabel();

        bEdit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bEdit.setText("Edit Animal");
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Animals name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Animals kind");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Chip number");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Owners phone to contact");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Owners email to contact");

        InputName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        InputName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNameActionPerformed(evt);
            }
        });

        InputChip.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        InputPhone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        InputEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cbxKind.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbxKind.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cat", "Dog" }));
        cbxKind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxKindActionPerformed(evt);
            }
        });

        InputID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lID.setText("Animals ID");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lWarning.setText("Choose Animal by ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(bEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lWarning)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(lID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(InputName)
                            .addComponent(cbxKind, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InputChip)
                            .addComponent(InputPhone)
                            .addComponent(InputEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(InputID))
                        .addGap(113, 113, 113))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lWarning)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(InputID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(InputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxKind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputChip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(46, 46, 46)
                .addComponent(bEdit)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxKindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxKindActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbxKindActionPerformed

    private void InputNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputNameActionPerformed

    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
        // TODO add your handling code here:
        try {
            db.edit(Integer.parseInt(InputID.getText()), InputName.getText(), cbxKind.getSelectedItem().toString(), Integer.parseInt(InputChip.getText()), Integer.parseInt(InputPhone.getText()), InputEmail.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please, privide valid data", "Invalid Data", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditAnimalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditAnimalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditAnimalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditAnimalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditAnimalFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InputChip;
    private javax.swing.JTextField InputEmail;
    private javax.swing.JTextField InputID;
    private javax.swing.JTextField InputName;
    private javax.swing.JTextField InputPhone;
    private javax.swing.JButton bEdit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JComboBox<String> cbxKind;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lID;
    private javax.swing.JLabel lWarning;
    // End of variables declaration//GEN-END:variables
    Database db;
    int keyCode;

    @Override
    public void keyTyped(KeyEvent e) {
        //dont put anything here
    }

    @Override
    public void keyPressed(KeyEvent e) {
         //dont put anything here
    }

    @Override
    public void keyReleased(KeyEvent e) {
        keyCode = e.getKeyChar();
        if(keyCode == KeyEvent.VK_0 || keyCode == KeyEvent.VK_1 || keyCode == KeyEvent.VK_2 || keyCode == KeyEvent.VK_3 || keyCode == KeyEvent.VK_4 || 
                keyCode == KeyEvent.VK_5 || keyCode == KeyEvent.VK_6 || keyCode == KeyEvent.VK_7 || keyCode == KeyEvent.VK_8 || keyCode == KeyEvent.VK_9
                || keyCode == KeyEvent.VK_BACK_SPACE) {
            
            try {
                int id = Integer.parseInt(InputID.getText());
                if (id != 0) {
                ChippedAnimal animal = db.getAnimal(id);
                    if (animal != null) {
                        lWarning.setText("");
                        InputName.setText(animal.getName());
                        cbxKind.setSelectedItem(animal.getKind());
                        InputChip.setText(animal.getChip().toString());
                        InputPhone.setText(animal.getPhone().toString());
                        InputEmail.setText(animal.getEmail());  
                    } else {
                        lWarning.setText("There is no Animal with given ID");
                        InputName.setText("");
                        cbxKind.setSelectedItem("");
                        InputChip.setText("");
                        InputPhone.setText("");
                        InputEmail.setText("");  
                    }
                }
                
            } catch (Exception ex) {
                lWarning.setText("It is not a valid ID number. Must be numeric");
            }

        } else {
            lWarning.setText("It is not a valid ID number. Must be numeric");
            InputName.setText("");
            cbxKind.setSelectedItem("");
            InputChip.setText("");
            InputPhone.setText("");
            InputEmail.setText(""); 
        }
    }
}
